services:
  api:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    container_name: recovery_api_dev
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - recovery-net

  mysql:
    image: mysql:8.0
    container_name: recovery_mysql_dev
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recovery
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - recovery-net

networks:
  recovery-net:
    external: true
